#!/bin/sh
LOGFILE="/tmp/hyperion.ng.log"
SERVICE_DIR="/media/developer/apps/usr/palm/services/org.webosbrew.hyperion.ng.loader.service"
HYPERION_DIR="$SERVICE_DIR/hyperion"

# Pfade für Qt6 und Bibliotheken
export LD_LIBRARY_PATH=$HYPERION_DIR/lib:$LD_LIBRARY_PATH
export QT_PLUGIN_PATH=$HYPERION_DIR/lib/plugins
export PYTHONHOME=$HYPERION_DIR/python

# Start aus dem bin/ Unterordner
OPENSSL_armcap=0 exec $HYPERION_DIR/bin/hyperiond -u /var/lib/hyperion "$@" > $LOGFILE 2>&1
